version: '3.8'

services:
  news-postgres:
    image: postgres:15
    container_name: news_postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - news-network
    restart: unless-stopped

  flask-app:
    image: chriss04/fake-news-model:v1
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - news-network
    restart: unless-stopped

  spring-app:
    image: chriss04/fake-news-backend:v2
    container_name: spring_app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "8080:8080"
    depends_on:
      - news-postgres
      - flask-app
    networks:
      - news-network
    restart: unless-stopped

  frontend-app:
    image: chriss04/fake-news-frontend:v1
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - spring-app
    networks:
      - news-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  news-network:
    driver: bridge