apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: fake-news
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z news-postgresql-ha-pgpool.fake-news.svc.cluster.local 5432; do echo waiting for db; sleep 3; done']
      containers:
        - name: spring-app
          image: chriss04/fake-news-backend
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: postgresql-ha-secret
