apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: fake-news
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: chriss04/fake-news-frontend
          ports:
            - containerPort: 80
