apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: fake-news
spec:
  selector:
    app: spring-app
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: fake-news
spec:
  type: ClusterIP
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: fake-news
spec:
  selector:
    app: flask-app
  ports:
    - port: 5000
      targetPort: 5000
