name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend_spring_app/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend_spring_app
        file: ./backend_spring_app/Dockerfile
        push: true
        tags: chriss04/backend-spring-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
